### ISSUE TITLE
Wishlist: A function to merge css-exprs

### ISSUE THREAD

**Issue by jessealama** [leafac/css-expr#2]
I'd love to see a function in `css-expr` that merges two css-exprs (which, I understand, are essentially [arbitrary S-expressions](https://github.com/leafac/css-expr/issues/1)). What I have in mind is the problem of making a single chunk of CSS that combines two (or more) chunks of CSS. It would be something like this:

```
;; in one place:
(define style-1 (css-expr (body max-width 650px)))

;; somewhere else
(define style-2 (css-expr (p line-height 1.2)))

;; merge these:
(define final-style (merge-css-exprs style-1 style-2)

;; would be equivalent to (css-expr (body max-width 650px) (p line-height 1.2))
```

**Comment by leafac** [comment]
Thanks again for contributing your ideas to CSS-expressions.

I don’t see a need for `merge-css-exprs` because I can think of two ways to achieve what you want:

1. Unquoting: `(css-expr ,@style-1 ,@style-2)`
2. `append`: `(append style-1 style-2)`

In general, I don’t see a reason for `css-expr` to provide functions for S-expression manipulation. Racket is already rich in that capacity and leveraging it is kind of the point of having CSS as S-expressions in the first place.

**Comment by jessealama** [comment]
Using unquoting is an elegant solution; that's essentially what I had in mind. Thanks!
